name: Build CV

on:
  push:
    branches:
      - master
    paths:
      - "src/**"
      - ".github/workflows/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Pandoc & wkhtmltopdf
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc wkhtmltopdf

      - name: Generate HTML & PDF
        run: |
          mkdir -p dist/templates
          cp templates/style.css dist/templates/style.css
          pandoc src/cv.md -s -c templates/style.css -o dist/index.html --metadata title="Curriculum Vitae - Maximiliano Correa"
          wkhtmltopdf --enable-local-file-access dist/index.html dist/cv.pdf

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          publish_dir: ./dist
