name: Build CV

on:
  push:
    branches:
      - main
    paths:
      - "src/**"
      - ".github/workflows/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Pandoc & wkhtmltopdf
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc wkhtmltopdf

      - name: Generate HTML & PDF
        run: |
          mkdir -p dist
          pandoc src/cv.md -s -c templates/style.css -o dist/index.html
          wkhtmltopdf dist/index.html dist/cv.pdf

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
